runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 2

# [START handlers]
handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.py
# [END handlers]